### ISSUE TITLE
Rocket Todo:

### ISSUE THREAD

**Issue by DannyvanderJagt** [DannyvanderJagt/suitcase#6]
**Server/Rocket**
- [x] Add `flow`
- [ ] Add a logger
- [ ] Add sockets/io.

**OSX**
- [ ] Clean up.
- [ ] Add `rocket-engine`
- [ ] Add `flow`
- [ ] Add a logger
- [ ] Add sockets/io.

**Comment by DannyvanderJagt** [comment]
Outdated since v0.3
